name: Dispatch E2E

on:
  workflow_dispatch:
    inputs:
      source_comment_id:
        description: "Comment ID that triggers this workflow"
        default: ""
        required: false
        
env:
  SOURCE_COMMENT_ID: ${{ github.event.inputs.source_comment_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "running e2e...."
          echo ${SOURCE_COMMENT_ID}
