name: Dispatch E2E

on:
  workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Restart workflow
        run: |
          URL=https://api.github.com/repos/${{github.repository}}/actions/runs/1515604086/rerun
          curl -X POST $URL
