name: Dispatch E2E

on:
  workflow_dispatch:
    inputs:
      source_comment_id:
        description: "Comment ID that triggers this workflow"
        default: ""
        required: false
        
env:
  SOURCE_COMMENT_ID: ${{ github.event.inputs.source_comment_id }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test 1
        run: |
          exit 1
  build:
    if: ${{ always() && github.event.inputs.source_comment_id != '' }}
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: test 2
        run: |
          echo "running e2e...."
          echo ${SOURCE_COMMENT_ID}
