name: Github Action

on:
  pull_request:

jobs:
  build_dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Testing
        run: |
          pr_labels="${{ toJson(github.event.pull_request.labels.*.name) }}"
          for row in $(echo "${toJson(github.event.pull_request.labels.*.name)}" | jq -r '.[]''); do
            echo $row
          done
