name: Increase e2e date-related data

on:
  workflow_dispatch:
    inputs:
      usergram-e2e-branch:
        description: "usergram-e2e branch"
        required: true
        default: master
      number-of-days:
        description: "Number of days to increase"
        required: true
        default: 30

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Run script
        run: |
          echo "testing..."

      - name: Checkout usergram-e2e repo
        uses: actions/checkout@v2
        with:
          repository: tongvantruong/usergram-e2e
          ref: main

      - name: Extract md5 from usergram-e2e repo
        id: extract-md5
        run: |
          usergram_e2e_cassandra_md5=$(grep 'md5:' data/cassandra/volume-cassandra.zip.dvc | sed 's/^.*: //')
          usergram_e2e_mysql_md5=$(grep 'md5:' data/mysql/volume-mysql.zip.dvc | sed 's/^.*: //')

          echo ::set-output name=usergram_e2e_cassandra_md5::$usergram_e2e_cassandra_md5
          echo ::set-output name=usergram_e2e_mysql_md5::$usergram_e2e_mysql_md5

      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Update md5
        run: |
          sed -i -e "s/md5:.*/md5:${steps.extract-md5.outputs.usergram_e2e_cassandra_md5}/g" ci/volume-cassandra.zip.dvc
          sed -i -e "s/md5:.*/md5:${steps.extract-md5.outputs.usergram_e2e_mysql_md5}/g" ci/volume-mysql.zip.dvc

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "github actions: Increase e2e date-related data"
          title: "[e2e][auto] Increase e2e date-related data"
          draft: false
          labels: auto-created
          base: main
          body: |
            # Why
            - Increase e2e date-related data by ${{ github.event.inputs.number-of-days }} days
            # What
            - Change dates in all e2e test cases
            - PR created automatically by https://github.com/tonvantruong/testing/actions/runs/${{ github.run_id }}
