name: Handle Slash Command

on: [pull_request]

jobs:
  handle_slash_command:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Slash command dispatch
        run: |
          echo ${{github.head_ref}}
          git commit --allow-empty -m "trigger GitHub actions"
          git push ${GITHUB_REF##*/} -f
