name: Handle Slash Command

on: [pull_request]

jobs:
  handle_slash_command:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Slash command dispatch
        run: |
          git commit --amend --no-edit --allow-empty
          echo ${GITHUB_REF##*/}
          git push ${GITHUB_REF##*/} -f
