name: (dev) auto-upload-external-lib

on:
  pull_request:
    types: opened

env:
  S3_EXTERNAL_LIB: s3://bebit-test-bucket/data-pipelines/external-lib
  PYMYSQL_FILE_NAME: PyMySQL-0.10.0-py2.py3-none-any.whl
  PYMYSQL_S3_URI: ${S3_EXTERNAL_LIB}/pymysql/${PYMYSQL_FILE_NAME}
  JOBLIB_FILE_NAME: joblib-0.17.0-py3-none-any.whl
  JOBLIB_S3_URI: ${S3_EXTERNAL_LIB}/joblib/${JOBLIB_FILE_NAME}

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download files from S3 to local
        run: |
          echo ${PYMYSQL_S3_URI}
          

          

