name: example
on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  check_action:
    runs-on: ubuntu-latest
    outputs:
      is_label: ${{ steps.define_type.outputs.is_label }}
    steps:
      - name: Define type
        id: define_type
        run: |
          echo "::set-output name=is_label::${{ github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'bug')}}"

  main:
    needs: [check_action]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show action name 1
        if: ${{ needs.check_action.outputs.is_label == true }}
        run: |
          echo "This workflow was triggered by 'labeled'"
      - name: Show action name 2
        if: ${{ !needs.check_action.outputs.is_label == false }}
        run: |
          echo "This workflow was triggered NOT by 'labeled'"
