name: Testing

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run E2E (chrome/firefox)"
        default: "chrome"
        required: false

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing
        run: |
          echo "123-{hash}"
