name: example
on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  check_action:
    runs-on: ubuntu-latest
    outputs:
      is_label: ${{ steps.define_type.outputs.is_label }}
    steps:
      - name: Define type
        id: define_type
        run: |
          echo ${{ github.event.action == 'labeled' }}
          echo ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
          echo ${{ github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'bug')}}
          echo "::set-output name=is_label::${{ github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'bug')}}"
  next:
    needs: [check_action]
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          a1={"hello": "world"} | jq '. + {foo: "FOO"}'
          echo ${a1}
          a2=$('{"hello": "world"}'' | jq '. + {foo: "FOO"}')
          echo ${a2}
          b='{"hello": "world"}'
          echo ${b}
          c=$($b | jq '. + {foo: "FOO"}')
          echo ${c}

  main:
    needs: [check_action, next]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show action name 1
        if: ${{ needs.check_action.outputs.is_label == 'true' }}
        run: |
          echo "This workflow was triggered by 'labeled'"
      - name: Show action name 2
        if: ${{ needs.check_action.outputs.is_label != 'true' }}
        run: |
          echo ${{ needs.check_action.outputs.is_label }}
          echo "This workflow was triggered NOT by 'labeled'"
