name: Testing

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run E2E (chrome/firefox)"
        default: "chrome"
        required: false

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing 23
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"state"}'
