name: Testing

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run E2E (chrome/firefox)"
        default: "chrome"
        required: false

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing
        run: |
          curl -X POST -H 'Content-Type: application/json' --data '{"state": "pending", "target_url": "https://locahost"}' https://${{ secrets.PAT3}}:x-oauth-basic@api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
