name: (dev) auto-upload-external-lib

on:
  pull_request:
    types: opened

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing
        run: |
          mkdir truong
          cd truong
          touch test.txt
