name: Testing

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run E2E (chrome/firefox)"
        default: "chrome"
        required: false

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "github actions: npm run update:e2e-date"
          title: "[e2e][auto] Change date in e2e tests"
          draft: false
          labels: auto-created
          branch: update-e2e-date-${ date +"%Y-%m-%d-%H-%M-%S" }
          body: |
            # Why
            - Hard code date in e2e need to be updated every 30 days.
            # What
            - Change dates in e2e tests
